# https://help.github.com/en/actions
name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    APP_ENV: 'test'
    APP_SECRET: 'secret'
    JWT_PRIVATE_KEY_PATH: 'config/jwt/test/private.pem'
    JWT_PUBLIC_KEY_PATH: 'config/jwt/test/public.pem'
    JWT_PASSPHRASE: 'passphrase'

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            # â€”â€” Setup Github actions ğŸ™ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            # https://github.com/actions/checkout (official)
            -   name: Checkout
                uses: actions/checkout@v2

            # https://github.com/shivammathur/setup-php (community)
            -   name: Setup PHP, extensions and composer with shivammathur/setup-php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: mbstring, intl, sqlite, json
                    ini-values: date.timezone= Europe/Paris
                    coverage: pcov
                env:
                    update: true

            # â€”â€” Composer ğŸ§™â€ï¸ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: composer install -o

            # â€”â€” Symfony ğŸµ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Check the Symfony console
                run: php bin/console -V

            ## â€”â€” Composer âœ¨ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Composer checks
                run: |
                    php composer validate
                    php composer normalize --dry-run

            ## â€”â€” Security âœ¨ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Security checks
                run: |
                    php vendor/bin/security-checker security:check

            ## â€”â€” Doctrine âœ¨ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Doctrine checks
                run: |
                    php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            ## â€”â€” Code âœ¨ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Code checks
                run: |
                    php vendor/bin/php-cs-fixer fix --verbose --dry-run
                    php vendor/bin/phpcs
                    php vendor/bin/phpmd src/,tests/ text phpmd.xml.dist
                    php vendor/bin/phpmnd src --extensions=default_parameter
                    php vendor/bin/phpstan analyse
                    php vendor/bin/psalm
                    php bin/console lint:yaml config/ --parse-tags
                    php bin/console lint:yaml fixtures/
                    php bin/console lint:yaml translations/
                    php bin/console lint:container

            ## â€”â€” Tests âœ… â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
            -   name: Run functionnal and unit tests
                run: |
                    vendor/bin/phpunit
